"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var routes_controller_1 = require("../controllers/routes.controller");
var routesRouter = (0, express_1.Router)();
var handler = new routes_controller_1.RoutesController();
routesRouter.post("/", function (req, res) { return handler.createRoute(req, res); });
routesRouter.put("/", function (req, res) { return handler.updateRoute(req, res); });
routesRouter.get("/", function (req, res) { return handler.getRoutes(req, res); });
routesRouter.get("/:id", function (req, res) { return handler.getRoute(req, res); });
routesRouter.delete("/:id", function (req, res) { return handler.delete(req, res); });
exports.default = routesRouter;
