services:
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: web.dockerfile
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - webnet
  #   depends_on:
  #     - api

  db:
    container_name: db
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    env_file:
      - ./api/.env
    networks:
      - apinet
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: api.dockerfile
      target: ${NODE_ENV}
    image: api:v1
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - ./api/.env
    networks:
      - webnet
      - apinet
    volumes:
      - ./api/src:/api/src
    depends_on:
      db:
        condition: service_healthy

networks:
  webnet:
    name: webnet
  apinet:
    name: apinet

volumes:
  pgdata:
    name: pgdata
