version: "3.9"

services:
  pgdb:
    image: postgres:16.4-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
      - /var/www/folio/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=folio
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432
  app:
    image: folio-api:v1
    ports:
      - 5100:3000
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
