"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var contents_routes_1 = require("./routes/contents.routes");
var users_routes_1 = require("./routes/users.routes");
var routes_routes_1 = require("./routes/routes.routes");
var roles_routes_1 = require("./routes/roles.routes");
var app = (0, express_1.default)();
app.use(express_1.default.json());
app.use("/contents", contents_routes_1.default);
app.use("/users", users_routes_1.default);
app.use("/routes", routes_routes_1.default);
app.use("/roles", roles_routes_1.default);
exports.default = app;
